controllers/AjaxController.php
<?php

namespace app\controllers;

use app\models\Clients;
use app\models\File;
use Yii;
use app\models\Orders;
use yii\web\UploadedFile;
use app\models\Directory;
use app\models\UploadForm;
Use yii\filters\AccessControl;

class AjaxController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];

    }

    public function actionUpload()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $order = new Orders();
        $model = new UploadForm();

        $orderId = Yii::$app->request->post()['orderId'];

        if($orderId <= 0) {
            $orderId = $order->getLastId();
        }

        if (Yii::$app->request->isPost) {
            $model->anyFiles = UploadedFile::getInstances($model, 'anyFiles');
            if($path = $model->upload(new Directory(), $orderId)) {
                $response = ['path' => $path];
                return $response;
            }
        }

        $response = ['error' => 'Upload faile'];
        return $response;
    }

    public function actionRemoveFile($id) {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $file = File::findOne($id);
        if($file->delete()) {
            return true;
        } else {
            return false;
        }
    }

    public function actionUpdateStep($orderId, $stepId) {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if (Yii::$app->request->isPost) {
            if (($order = Orders::findOne($orderId)) !== null) {

                $order->step_id = $stepId;
                if($order->save()) {
                    return true;
                }
            }
        }

        return false;
    }

    public function actionUpdateStepClient($clientId, $stepId)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if (Yii::$app->request->isPost) {
            if (($client = Clients::findOne($clientId)) !== null) {

                $client->step_client_id = $stepId;
                if($client->save()) {
                    return true;
                }
            }
        }

        return false;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Orders;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Steps;
use app\models\Board;
use app\models\BoardOrder;

class SiteController extends Controller
{

    public $wrapperClass;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['boards-order, board-detail-order'],
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return !Yii::$app->user->identity->candelete;
                        }
                    ],
                ],
            ],
        ];
    }    public function init() {
        parent::init();

    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->wrapperClass = 'desc-page';

        $stepsObj = new Steps();
        $stepOrders = $stepsObj->getOrdersWithSteps();

        return $this->render('index', [
            'steps' => $stepOrders,
        ]);
    }

    public function actionBoardsClient()
    {
        $boards = Board::find()->all();

        return $this->render('boards-client', [
            'boards' => $boards,
        ]);
    }

    public function actionBoardDetailClient($id)
    {
        $this->wrapperClass = 'desc-page';

        $boardObj = new Board();
        $board = $boardObj->getStepsWithClients($id);

        return $this->render('board-item-client', [
            'board' => $board,
            'boardId' => $id,
        ]);
    }

    public function actionBoardsOrder()
    {
        $boards = BoardOrder::find()->all();

        return $this->render('boards-order', [
            'boards' => $boards,
        ]);
    }

    public function actionBoardDetailOrder($id)
    {
        $this->wrapperClass = 'desc-page';

        $boardObj = new BoardOrder();
        $steps = $boardObj->getStepsWithOrders($id);

        return $this->render('board-item-order', [
            'steps' => $steps,
            'boardId' => $id,
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/site/board-item-client.php
<?php

/* @var $this yii\web\View */

$this->title = (!empty($board)) ? $board['title'] : 'Этапов не найдено';
use yii\helpers\Url;
use kartik\sortable\Sortable;
use yii\helpers\StringHelper;
use yii\bootstrap\Modal;
use app\assets\DetailBoardClient;

DetailBoardClient::register($this);
?>
<div class="desc-page-container">
    <div class="page-container-width">

        <div class="row">
            <?php if(!empty($board['items'])):?>
            <?php foreach ($board['items'] as $key=>$itemStep):
                $stepTitle = $itemStep['title'];
                $stepId = $itemStep['id'];

                if(isset($itemStep['clients'])) {
                    $countSteps = count($itemStep['clients']);
                } else {
                    $countSteps = 0;
                }

                ?>
                <div class="step-column" id="<?= $key?>step">
                    <div class="step-title">
                        <div class="bold-title"><?=StringHelper::truncate($stepTitle, 24)?></div>
                        <span class="stagevalue">
                            <span class="value">
                                <small>Клиентов <span class="count-clients-item"><?= $countSteps?></span></small>
                            </span>
                        </span>
                    </div>
                    <?php
                    $items = [];
                    if($countSteps) {
                        foreach($itemStep['clients'] as $itemClient) {

                            $clientId = $itemClient['client_id'];
                            $clientName = $itemClient['client_name'];
                            $clientPhone = $itemClient['client_cellphone'];
                            $countOrders = $itemClient['count_orders'];
                            $deadline = $itemClient['deadline'];

                            $diff_date = $itemClient['diff_date'];

                            $url = Url::to(['clients/view', 'id' => $clientId]);
                            $items[]['content'] = "
                                <div class='box box-default order-item collapsed-box' id='{$clientId}' data-parent-step='{$key}step'>
                                    <div class='deadline {$deadline}'></div>
                                    <div class='box-header'>
                                        <span class='box-title title-order'>{$clientName}</span>
                                        <div class='box-tools pull-right'>
                                            <div><a href='{$url}'>
                                                <i class='fa fa-eye' aria-hidden='true'></i>
                                            </a></div>
                                            <div><a href='#' class='btn btn-box-tool' data-widget='collapse'>
                                                <i class='fa fa-plus'></i>
                                            </a></div>
                                        </div>
                                                                                
                                    </div>
                                    <div class='box-body'>
                                        <span class='box-body-text'>Телефон: {$clientPhone}</span><br>
                                        <span class='box-body-text'>Количество заказов: {$countOrders}</span><br>
                                    </div>
                                </div>
                               ";
                        }
                    }

                    echo Sortable::widget([
                        'connected'=>true,
                        'options' => [
                            'data-step'=>$stepId,
                            'data-url-update' => Url::to(['ajax/update-step-client']),
                        ],
                        'items' => $items,
                        'pluginEvents' => [
                            'sortupdate' => "function(e, e2) {
                                var currentElementSelector = $(e2.item.context).find('div');
                                
                                var currentStep = {$stepId};
                                var currentId = currentElementSelector.attr('id');                                
                                var oldStepId =  $(currentElementSelector).data('parent-step');
                                
                                currentElementSelector.data('parent-step', currentStep + 'step');
                                                                                             
                                //Этап from
                                var oldStepObj = $('#' + oldStepId);
                                
                                var countClientsItemFrom = oldStepObj.find('.count-clients-item');
                                var countClientsItemFromValue = countClientsItemFrom.text();
                                countClientsItemFromValue--;
                                countClientsItemFrom.text(countClientsItemFromValue);
                                                              
                                //Этап to
                                var currentStepObj = $('#' + currentStep + 'step');
                                
                                var countClientsItemTo = currentStepObj.find('.count-clients-item');
                                var countClientsItemToValue = countClientsItemTo.text();
                                countClientsItemToValue++;
                                countClientsItemTo.text(countClientsItemToValue);
                                
                                $.ajax({ type: 'POST',
                                    url: '/ajax/update-step-client?clientId='+currentId+'&stepId='+currentStep,
                                    success: function(data){
                                        console.log(data);
                                    }
                                });
                            }",
                        ],
                    ]);
                    ?>
                </div>
            <?php endforeach;?>
            <div class="step-column add-client-button-column">
                <a href="<?= Url::to(['ajax-step-client/create', 'boardId' => $boardId])?>" id="create-step-client" class="btn">
                    Создать этап клиента
                </a>
            </div>
            <?php else:?>
                <div class="step-column add-client-button-column">
                    <a href="<?= Url::to(['ajax-step-client/create', 'boardId' => $boardId])?>" id="create-step-client" class="btn">
                        Создать этап клиента
                    </a>
                </div>
            <?php endif;?>
        </div>



    </div>
</div>
<div class="clearfix"></div>
<?php
$this->beginBlock('step-client-modal-block');
?>
<?php
Modal::begin([
    'header' => 'Создать этап клиента',
    'id' => 'step-client-modal'
]);
Modal::end();
?>
<?php
$this->endBlock();
?>

views/site/board-item-order.php
<?php

/* @var $this yii\web\View */

$this->title = 'Mini crm';
use yii\helpers\Url;
use kartik\sortable\Sortable;
use yii\helpers\StringHelper;
use yii\bootstrap\Modal;
use app\assets\DetailBoardOrderAsset;

DetailBoardOrderAsset::register($this);
?>
<div class="desc-page-container">
    <div class="page-container-width">
        <div class="row">
        <?php if(!empty($steps)):?>
            <?php foreach ($steps as $key=>$itemStep):
                $stepTitle = $itemStep['title'];
                $stepId = $itemStep['id'];

                if(isset($itemStep['orders'])) {
                    $countSteps = count($itemStep['orders']);
                } else {
                    $countSteps = 0;
                }

                ?>
                <div class="step-column" id="<?= $key?>step">
                    <div class="step-title">
                        <div class="bold-title"><?=StringHelper::truncate($stepTitle, 24)?></div>
                        <span class="stagevalue">
                                <span class="value">
                                    <span class="all-sum-step"><?= $itemStep['all_sum']?></span> р.
                                    <small>Заказов <span class="count-orders-item"><?= $countSteps?></span></small>
                                </span>
                            </span>
                    </div>
                    <?php
                    $items = [];
                    if($countSteps) {
                        foreach($itemStep['orders'] as $itemOrder) {

                            $orderId = $itemOrder['order_id'];
                            $orderTitle = $itemOrder['order_title'];
                            if(!is_null($itemOrder['full_sum'])) {
                                $full_sum = $itemOrder['full_sum'];
                            } else {
                                $full_sum = 0;
                            }
                            $client_name = $itemOrder['client_name'];
                            $developer_name = $itemOrder['developer_name'];
                            $delivery_date = $itemOrder['delivery_date'];
                            $clear_sum = $itemOrder['clear_sum'];
                            $client_loyalty = $itemOrder['client_loyalty'];
                            $client_id = $itemOrder['client_id'];
                            $deadline = $itemOrder['deadline'];

                            $url = Url::to(['orders/view', 'id' => $orderId]);
                            $client_url = Url::to(['clients/view', 'id' => $client_id]);
                            $items[]['content'] = "
                                <div class='box box-default order-item collapsed-box' id='{$orderId}' data-parent-step='{$key}step'>
                                <div class='deadline {$deadline}'></div>
                                    <div class='box-header'>
                                        <span class='box-title title-order'>{$orderTitle}</span>
                                        <div>
                                            <small><span class='detail value full-sum-item'>{$full_sum} р.</span></small>
                                            <small><span class='detail value client-name-item'>{$client_name}</span></small>
                                                      
                                        </div>
                                        <div class='box-tools pull-right'>
                                            <div class='client_loyalty hidden'>{$client_loyalty}</div>
                                            <div><a href='{$url}'>
                                                <i class='fa fa-eye' aria-hidden='true'></i>
                                            </a></div>
                                            <div><a href='{$client_url}'>
                                                <i class='fa fa-address-card' aria-hidden='true'></i>
                                            </a></div>
                                            <div><a href='#' class='btn btn-box-tool' data-widget='collapse'>
                                                <i class='fa fa-plus'></i>
                                            </a></div>
                                        </div>                               
                                    </div>
                                    <div class='box-body'>
                                        <span class='box-body-text'>Полная сумма: {$full_sum}</span><br>
                                        <span class='box-body-text'>Программист: {$developer_name}</span><br>
                                        <span class='box-body-text'>Дата сдачи: {$delivery_date}</span><br>
                                        <span class='box-body-text'>Чистая прибыль: {$clear_sum}</span><br>
                                    </div>
                                </div>
                               ";
                        }
                    }

                    echo Sortable::widget([
                        'connected'=>true,
                        'options' => [
                            'data-step'=>$stepId,
                            'data-url-update' => Url::to(['ajax/update-step']),
                        ],
                        'items' => $items,
                        'pluginEvents' => [
                            'sortupdate' => "function(e, e2) {
                                var currentElementSelector = $(e2.item.context).find('div');
                                
                                var currentStep = {$stepId};
                                var currentId = currentElementSelector.attr('id');                                
                                var oldStepId =  $(currentElementSelector).data('parent-step');

                                currentElementSelector.data('parent-step', currentStep + 'step');
                             
                                //Пересчет заказов и суммы в этапе
                                var fullSumItem = parseInt(currentElementSelector.find('.full-sum-item').text());
                                if(Number.isNaN(fullSumItem)) {
                                    fullSumItem = 0;
                                }
                                
                                //Этап from
                                var oldStepObj = $('#' + oldStepId);
                                
                                var countOrdersItemFrom = oldStepObj.find('.count-orders-item');
                                var countOrdersItemFromValue = countOrdersItemFrom.text();
                                countOrdersItemFromValue--;
                                countOrdersItemFrom.text(countOrdersItemFromValue);
                                
                                var allSumStepFrom = oldStepObj.find('.all-sum-step');
                                var allSumStepFromValue = parseInt(allSumStepFrom.text()); 
                                allSumStepFrom.text(allSumStepFromValue - fullSumItem);
                              
                                //Этап to
                                var currentStepObj = $('#' + currentStep + 'step');
                                
                                var countOrdersItemTo = currentStepObj.find('.count-orders-item');
                                var countOrdersItemToValue = countOrdersItemTo.text();
                                countOrdersItemToValue++;
                                countOrdersItemTo.text(countOrdersItemToValue);
                                
                                var allSumStepTo = currentStepObj.find('.all-sum-step');
                                var allSumStepToValue = parseInt(allSumStepTo.text()); 
                                allSumStepTo.text(allSumStepToValue + fullSumItem);
                                
                                $.ajax({ type: 'POST',
                                    url: '/ajax/update-step?orderId='+currentId+'&stepId='+currentStep,
                                    success: function(data){
                                        console.log(data);
                                    }
                                });                                
                            }",
                        ],
                    ]);
                    ?>
                </div>
            <?php endforeach;?>
            <div class="step-column add-client-button-column">
                <a href="<?= Url::to(['ajax-step-order/create', 'boardId' => $boardId])?>" id="create-step-order" class="btn">
                    Создать этап заказа
                </a>
            </div>
            <?php else:?>
            <div class="step-column add-client-button-column">
                <a href="<?= Url::to(['ajax-step-order/create', 'boardId' => $boardId])?>" id="create-step-order" class="btn">
                    Создать этап заказа
                </a>
            </div>
            <?php endif;?>
        </div>



    </div>

</div>
    <div class="clearfix"></div>
<?php
$this->beginBlock('step-client-modal-block');
?>
<?php
Modal::begin([
    'header' => 'Создать этап заказа',
    'id' => 'step-order-modal'
]);
Modal::end();
?>
<?php
$this->endBlock();
?>

views/site/boards-client.php
<?php
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use app\assets\BoardsClientsAsset;

BoardsClientsAsset::register($this);

$this->title = 'Персональные доски клиентов';
?>

<div class="boards-page-board-section-header">
    <h3 class="boards-page-board-section-header-name"><?= Html::encode($this->title) ?></h3>
</div>

<ul class="boards-page-board-section-list" id="">
    <span id="boards-list-ajax">
        <?php foreach ($boards as $item):?>
            <li class="boards-page-board-section-list-item">
                <a class="board-tile" href="<?=Url::to(['/site/board-detail-client', 'id' => $item->id])?>">
                    <span class="board-tile-details is-badged">
                        <span title="CRM мини" dir="auto" class="board-tile-details-name"><?=$item->title?></span>
                    </span>
                </a>
            </li>
        <?php endforeach;?>
    </span>
    <li class="boards-page-board-section-list-item">
        <a href="<?=Url::to(['ajax-board-client/create'])?>" class="board-tile mod-add" id="create-board">
            <span class="board-tile-details is-badged">
				<span title="CRM мини" dir="auto" class="board-tile-details-name">Создать новую доску…</span>
            </span>
        </a>
    </li>
</ul>

<?php
Modal::begin([
    'header' => 'Создать новую доску',
    'id' => 'board-modal'
]);
Modal::end();
?>

views/site/boards-order.php
<?php
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use app\assets\OrdersBoardsAsset;

OrdersBoardsAsset::register($this);

$this->title = 'Персональные доски заказов';
?>

    <div class="boards-page-board-section-header">
        <h3 class="boards-page-board-section-header-name"><?= Html::encode($this->title) ?></h3>
    </div>

    <ul class="boards-page-board-section-list" id="">
    <span id="boards-order-list-ajax">
        <?php foreach ($boards as $item):?>
            <li class="boards-page-board-section-list-item">
                <a class="board-tile" href="<?=Url::to(['/site/board-detail-order', 'id' => $item->id])?>">
                    <span class="board-tile-details is-badged">
                        <span title="CRM мини" dir="auto" class="board-tile-details-name"><?=$item->title?></span>
                    </span>
                </a>
            </li>
        <?php endforeach;?>
    </span>
        <li class="boards-page-board-section-list-item">
            <a href="<?=Url::to(['ajax-board-order/create'])?>" class="board-tile mod-add" id="create-board-order">
            <span class="board-tile-details is-badged">
				<span title="CRM мини" dir="auto" class="board-tile-details-name">Создать новую доску…</span>
            </span>
            </a>
        </li>
    </ul>

<?php
Modal::begin([
    'header' => 'Создать новую доску',
    'id' => 'board-order-modal'
]);
Modal::end();
?>

views/site/customer_from.php
<?php

/* @var $this yii\web\View */

$this->title = 'Откуда пришел клиент';
use yii\helpers\Url;
?>



<div class="row">
    <div class="col-md-12">
        <h1>Откуда пришел клиент</h1>
        <table class="table customer-from">
            <thead>
            <tr>
                <th>Откуда пришел</th>
                <th>Количесвто</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($customerFrom as $key=>$item):?>
                <tr>
                    <td><?=$item['customer_from']?></td>
                    <td><?=$item['total']?></td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>