models/Orders.php
<?php

namespace app\models;

use Yii;
use \yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\web\UploadedFile;
use app\models\File;
use yii\db\Query;

/**
 * This is the model class for table "orders".
 *
 * @property integer $id
 * @property string $title
 * @property string $project_link
 * @property string $accesses
 * @property integer $full_sum
 * @property integer $clear_sum
 * @property integer $payed_sum
 * @property integer $count_steps
 * @property string $created_at
 * @property string $updated_at
 * @property integer $client_id
 * @property integer $developer_id
 * @property integer $step_id
 * @property integer $observer_id
 *
 * @property File[] $files
 * @property Clients $client
 * @property Developers $developer
 * @property User $observer
 * @property Steps $step
 */
class Orders extends ActiveRecord
{
    /**
     * @var UploadedFile[]
     */
    //public $files;

    /**
     * @var string Temp files json
     */
    public $tempFiles;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['accesses'], 'string'],
            [['full_sum', 'clear_sum', 'payed_sum', 'count_steps', 'client_id', 'developer_id', 'step_id', 'observer_id'], 'integer'],
            [['created_at', 'updated_at', 'delivery_date'], 'safe'],
            [['title', 'project_link'], 'string', 'max' => 255],
            [['title'], 'unique'],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Clients::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['developer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Developers::className(), 'targetAttribute' => ['developer_id' => 'id']],
            [['observer_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['observer_id' => 'id']],
            [['step_id'], 'exist', 'skipOnError' => true, 'targetClass' => Steps::className(), 'targetAttribute' => ['step_id' => 'id']],
            [['files'], 'file', 'skipOnEmpty' => true, 'maxFiles' => 4, 'maxSize' => 20971520],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'project_link' => 'Ссылка на проект',
            'accesses' => 'Доступы к проекту(текстовый)',
            'full_sum' => 'Сумма общая',
            'clear_sum' => 'Сумма чистая',
            'payed_sum' => 'Сумма оплаченная',
            'count_steps' => 'Кол. этапов',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата изменения',
            'files' => 'Файлы',
            'client_id' => 'Клиент',
            'developer_id' => 'Исполнитель',
            'step_id' => 'Этап',
            'observer_id' => 'Наблюдатель',
            'tempFiles' => 'Файлы',
            'delivery_date' => 'Дата сдачи',
            'sum_group' => 'Суммы',
            'participants' => 'Участники',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFiles()
    {
        return $this->hasMany(File::className(), ['order_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Clients::className(), ['id' => 'client_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDeveloper()
    {
        return $this->hasOne(Developers::className(), ['id' => 'developer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getObserver()
    {
        return $this->hasOne(User::className(), ['id' => 'observer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStep()
    {
        return $this->hasOne(Steps::className(), ['id' => 'step_id']);
    }

    /**
     * Return max order id
     *
     * @return integer Max order id  + 1
     */
    public function getLastId()
    {
        $maxId = (new \yii\db\Query())
            ->select('auto_increment')
            ->from('information_schema.tables')
            ->where(['table_name' => 'orders'])
            ->one();
        return $maxId['auto_increment'];
    }

    /**
     * Writes rows to a table File
     *
     * @param \app\models\File $file
     * @param $tempFiles array
     * @param $order_id integer
     */
    public function addFiles($tempFiles, $order_id) {
        if(is_null($tempFiles)) {
            return false;
        }
        foreach ($tempFiles as $itemFile) {
            $file = new File();
            $file->order_id = $order_id;
            $file->title = $itemFile['name'];
            $file->path = $itemFile['path'];
            $file->save();
            unset($file);
        }
    }

    /**
     * Return uniques customer from column values
     *
     * @return array|ActiveRecord[]
     */
    /*
    public function getCustomerFrom() {
        $subQuery = (new Query())->select('COUNT(customer_from) AS total');
        return $query = (new Query())
            ->select(['customer_from', 'total' => $subQuery])
            ->from('orders')
            ->groupBy('customer_from')
            ->orderBy(['total' => SORT_DESC])
            ->all();
    }
    */
}

controllers/AjaxController.php
<?php

namespace app\controllers;

use app\models\Clients;
use app\models\File;
use Yii;
use app\models\Orders;
use yii\web\UploadedFile;
use app\models\Directory;
use app\models\UploadForm;
Use yii\filters\AccessControl;

class AjaxController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];

    }

    public function actionUpload()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $order = new Orders();
        $model = new UploadForm();

        $orderId = Yii::$app->request->post()['orderId'];

        if($orderId <= 0) {
            $orderId = $order->getLastId();
        }

        if (Yii::$app->request->isPost) {
            $model->anyFiles = UploadedFile::getInstances($model, 'anyFiles');
            if($path = $model->upload(new Directory(), $orderId)) {
                $response = ['path' => $path];
                return $response;
            }
        }

        $response = ['error' => 'Upload faile'];
        return $response;
    }

    public function actionRemoveFile($id) {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $file = File::findOne($id);
        if($file->delete()) {
            return true;
        } else {
            return false;
        }
    }

    public function actionUpdateStep($orderId, $stepId) {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if (Yii::$app->request->isPost) {
            if (($order = Orders::findOne($orderId)) !== null) {

                $order->step_id = $stepId;
                if($order->save()) {
                    return true;
                }
            }
        }

        return false;
    }

    public function actionUpdateStepClient($clientId, $stepId)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if (Yii::$app->request->isPost) {
            if (($client = Clients::findOne($clientId)) !== null) {

                $client->step_client_id = $stepId;
                if($client->save()) {
                    return true;
                }
            }
        }

        return false;
    }
}

controllers/OrdersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Orders;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\File;
use app\models\Directory;
use app\models\UploadForm;
use yii\filters\AccessControl;

/**
 * OrdersController implements the CRUD actions for Orders model.
 */
class OrdersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'matchCallback' => function ($rule, $action) {
                            return !Yii::$app->user->identity->candelete;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Orders models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Orders::find(),
            'sort'=> ['defaultOrder' => ['id'=>SORT_DESC]],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Orders model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $filesContent = File::getFilesContent($id);

        return $this->render('view', [
            'model' => $model,
            'filesContent' => $filesContent,
        ]);
    }

    /**
     * Creates a new Orders model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Orders();
        $modelUpload = new UploadForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $tempFiles = json_decode(Yii::$app->request->post()['Orders']['tempFiles'], true);
            $model->addFiles($tempFiles, $model->id);

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'modelUpload' => $modelUpload,
            ]);
        }
    }

    /**
     * Updates an existing Orders model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelUpload = new UploadForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $tempFiles = json_decode(Yii::$app->request->post()['Orders']['tempFiles'], true);
            $model->addFiles($tempFiles, $model->id);

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'modelUpload' => $modelUpload,
            ]);
        }

    }

    /**
     * Deletes an existing Orders model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        File::deleteAll(['order_id' => $id]);

        $directory = new Directory();
        $directory->deleteDirectory($id);

        return $this->redirect(['index']);
    }

    /**
     * Finds the Orders model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Orders the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Orders::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionDownload($path)
    {
        return \Yii::$app->response->sendFile($path);
    }
}

views/orders/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use yii\helpers\Url;
use dosamigos\datepicker\DatePicker;
use yii\bootstrap\Modal;
use app\assets\AjaxClientsAsset;

AjaxClientsAsset::register($this);

/* @var $this yii\web\View */
/* @var $model app\models\Orders */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="orders-form">

    <?php $form = ActiveForm::begin([
            'options' => [
                'enctype' => 'multipart/form-data',
            ]
    ]) ?>

    <?= $form->field($model, 'tempFiles')->hiddenInput()->label(false) ?>
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'project_link')->textInput(['maxlength' => true]) ?>
                </div>
            </div>

            <?= $form->field($model, 'accesses')->textarea(['rows' => 3]) ?>

            <div class="row">
                <div class="col-md-2">
                    <?= $form->field($model, 'full_sum')->textInput() ?>
                </div>
                <div class="col-md-2">
                    <?= $form->field($model, 'clear_sum')->textInput() ?>
                </div>
                <div class="col-md-2">
                    <?= $form->field($model, 'payed_sum')->textInput() ?>
                </div>
                <div class="col-md-2">
                    <?= $form->field($model, 'count_steps')->textInput() ?>
                </div>
                <div class="col-md-4">
                    <?= $form->field($model, 'developer_id')
                        ->dropDownList(\app\models\Developers::find()
                            ->select(['nick', 'id'])
                            ->indexBy('id')
                            ->column(), ['prompt' => '']) ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'step_id')
                        ->dropDownList(\app\models\BoardOrder::getBoardsWithSteps(), ['prompt' => 'Выберите этап']) ?>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'observer_id')
                        ->dropDownList(\app\models\User::find()
                            ->select(['username as name', 'id'])
                            ->indexBy('id')
                            ->column(), ['prompt' => '']) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <?= $form->field($model, 'client_id')
                        ->dropDownList(\app\models\Clients::find()
                            ->select(['name', 'id'])
                            ->indexBy('id')
                            ->column(), ['prompt' => '']) ?>
                </div>
                <div class="col-md-3">
                    <div class="add-client">
                        <a href="<?= Url::to(['ajax-client/create'])?>" id="add-client" class="btn btn-primary">
                            Создать клиента
                        </a>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>


        </div>
        <div class="col-md-2">

            <?= $form->field($model, 'delivery_date')->widget(
                DatePicker::className(), [
                'inline' => true,
                'language' => 'ru',
                'template' => '{input}',
                'clientOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd'
                ]
            ]);?>
        </div>


        <div class="col-md-9">
            <?php $form2= ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

            <?= $form2->field($modelUpload, 'anyFiles[]')->widget(FileInput::classname(), [
                'options' => ['multiple' => true],
                'pluginOptions' => [
                    'uploadUrl' => Url::to(['/ajax/upload']),
                    'uploadExtraData' => [
                        'orderId' => $model->id,
                    ],
                    'showPreview' => true,
                    'showCaption' => true,
                    'showRemove' => false,
                    'showUpload' => true,
                    'previewFileType' => 'any',
                    'maxFileSize' => 20971520,
                ],
                'pluginEvents' => [
                    'fileuploaded' => "
                        function(event, data, previewId, index) {                    
                            var image = {
                              name: data.files[index].name,
                              path: data.response.path,
                            };
                           
                            console.log(image);
                            console.log(index);
                            console.log(data.files[index].name);
                            
                            var resultJsonInput = $('#orders-tempfiles').val();
                            if(resultJsonInput.length > 0) {
                                var resultArray = JSON.parse(resultJsonInput);
                            } else {
                                var resultArray = Array();
                            }
                            resultArray.push(index);
                            resultArray[index] = image;
                            var JsonResult = JSON.stringify(resultArray);
                            $('#orders-tempfiles').val(JsonResult);
                        }
                    ",
                ],
            ]);?>
            <?php ActiveForm::end() ?>
        </div>
    </div>
</div>

<?php
Modal::begin([
    'header' => 'Создать клиента',
    'id' => 'user-modal'
]);
Modal::end();
?>

views/orders/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Orders */

$this->title = 'Создать заказ';
$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modelUpload' => $modelUpload,
    ]) ?>

</div>

views/orders/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use app\models\File;
use yii\helpers\StringHelper;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Заказы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="orders-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Создать заказ', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <div class="table-responsive">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'responsive'=>true,
                'hover'=>true,
                'tableOptions' => [
                    'class' => 'table table-striped table-bordered'
                ],
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    [
                        'attribute' => 'title',
                        'value' => function($data){
                            $title = StringHelper::truncate($data->title, 30);
                            $link = ($data->project_link) ? Html::a('Ссылка', $data->project_link, ['target'=>'_blank']) : "";
                            return "
                                <div>{$title}</div>
                                <div>{$link}</div>
                            ";
                        },
                        'format' => 'html',
                    ],
                    [
                        'attribute' => 'sum_group',
                        'value' => function($data){
                            $full_sum = ($data->project_link) ? $data->full_sum : '<span class="not-set">(не задано)</span>';
                            $clear_sum = ($data->clear_sum) ? $data->clear_sum : '<span class="not-set">(не задано)</span>';
                            $payed_sum = ($data->payed_sum) ? $data->payed_sum : '<span class="not-set">(не задано)</span>';
                            return "
                                <div>Сумма общая: {$full_sum}</div>
                                <div>Сумма чистая: {$clear_sum}</div>
                                <div>Сумма оплаченная: {$payed_sum}</div>
                                ";
                        },
                        'format' => 'html',
                    ],
                    [
                        'attribute' => 'participants',
                        'value' => function($data){
                            $developer = ($data->developer) ? $data->developer->nick : '<span class="not-set">(не задано)</span>';
                            $observer = ($data->observer) ? $data->observer->username : '<span class="not-set">(не задано)</span>';
                            $client = ($data->client) ? $data->client->name : '<span class="not-set">(не задано)</span>';
                            return "
                                <div>Исполнитель: {$developer}</div>
                                <div>Наблюдатель: {$observer}</div>
                                <div>Клиент: {$client}</div>
                                ";
                        },
                        'format' => 'html',
                    ],
                    'count_steps',
                    //'created_at',
                    //'updated_at',
                    [
                        'attribute' => 'step_id',
                        'value' => function($data){
                            return ($data->step) ? $data->step->title : "";
                        },
                    ],
                    [
                        'attribute' => 'files',
                        'format' => 'html',
                        'value' => function($data){
                            return File::getFilesContent($data->id);
                        },
                    ],
                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
    </div>

</div>

views/orders/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Orders */

$this->title = 'Обновить заказ: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Обновить';
?>
<div class="orders-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modelUpload' => $modelUpload,
    ]) ?>

</div>

views/orders/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\StringHelper;
use rmrevin\yii\module\Comments;

/* @var $this yii\web\View */
/* @var $model app\models\Orders */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="orders-view">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Обновить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'title',
            [
                'attribute' => 'project_link',
                'value' => ($model->project_link) ?
                    Html::a(StringHelper::truncate($model->project_link, 40), $model->project_link, ['target'=>'_blank'])
                    : "",
                'format' => 'html',
            ],
            'accesses:ntext',
            'full_sum',
            'clear_sum',
            'payed_sum',
            'count_steps',
            'created_at',
            'updated_at',
            'delivery_date',
            [
                'attribute' => 'client_id',
                'value' => ($model->client) ? $model->client->name : "",
            ],
            [
                'attribute' => 'developer_id',
                'value' => ($model->developer) ? $model->developer->name : "",
            ],
            [
                'attribute' => 'step_id',
                'value' => ($model->step) ? $model->step->title : "",
            ],
            [
                'attribute' => 'observer_id',
                'value' => ($model->observer) ? $model->observer->username : "",
            ],
            [
                'attribute' => 'files',
                'value' => $filesContent,
                'format' => 'html',
            ],
        ],
    ]) ?>

    <?php
    echo Comments\widgets\CommentListWidget::widget([
        'entity' => (string) $model->id,
    ]);
    ?>

</div>